### ISSUE TITLE
README.md for project

### ISSUE THREAD

**Issue by pcgeek86** [neilpeterson/windows-dockerfile#1]
Could you add a README for this, that specifies details such as:

- Required version of Windows Server 2016 (does it run on Nano Server?)
- Required version of Docker
- Prerequisite configuration of Windows Server OS, if applicable

This is looking pretty awesome. :smile: 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by neilpeterson** [comment]
Thanks Trevor, I've added README files and a few new dockerfiles, more on the way.

**Comment by pcgeek86** [comment]
@neilpeterson thanks! Taking a look!
